(* Grammar for Practice 5 Language in EBNF *)
(* Languages and Compilers Design *)

program    ::= { statement } exit ;

statement  ::= decl | assign | if_stmt ;

decl       ::= type [ "mut" ] ident "{" expr "}" NL ;

type       ::= "i32" | "i64" | "bool" ;

assign     ::= ident ":=" expr NL ;

exit       ::= "exit" factor NL ;

if_stmt    ::= "if" expr NL block [ "else" NL block ] ;

block      ::= "{" NL { statement } [ exit ] "}" NL ;

expr       ::= arith [ ( "==" | "!=" ) arith ] ;

arith      ::= term { ( "+" | "-" ) term } ;

term       ::= factor { "*" factor } ;

factor     ::= number | "true" | "false" | ident | "!" factor ;
